### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rist** [schwa/swiftlint-autodetect#1]
Tried a fresh install of pipx and swiftlint-autodetect and got this error:

```
ERROR: Cannot unpack file .... /swiftlint-autodetect.git (downloaded from ..../pip-req-build-vgyq0bhz, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of ..../pip-req-build-vgyq0bhz
Cannot determine package name from spec 'https://github.com/schwa/swiftlint-autodetect.git'. Check package spec for errors.
```

(By the way - thanks for creating this tool - I used to do basically the same thing manually for lots of projects and this will be a great time saver)

**Comment by schwa** [comment]
Ah yes. It's `pipx install git+https://github.com/schwa/swiftlint-autodetect.git`

Thanks for reporting!
