### ISSUE TITLE
No output from `swiftlint-autocomplete count`

### ISSUE THREAD

**Issue by nbeadman** [schwa/swiftlint-autodetect#4]
Thanks for this amazing tool!

`swiftlint-autocomplete generate` works great and produces the output as expected. However, `count` does appear to do anything. 

> time swiftlint-autodetect generate «path»
> 1.79s user 0.46s system 91% cpu 2.463 total

> time swiftlint-autodetect count «path»
> 0.09s user 0.02s system 93% cpu 0.123 total

Is there any debugging I can do to figure out what is going on?

**Comment by schwa** [comment]
Yeah looks like count was completely broken for 2 years :-) Fix hopefully coming.

**Comment by nbeadman** [comment]
Amazing turnaround. Works for me now
